# -*- coding: utf-8 -*-
"""0630_AQI_date.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANkK6mXfzThOZOYtbvlLpDcELmeEE2Ff
"""



import requests

url = 'https://data.moenv.gov.tw/api/v2/aqx_p_432?api_key=e8dd42e6-9b8b-43f8-991e-b3dee723a52d&limit=1000&sort=ImportDate desc&format=CSV'
response = requests.get(url)
print(response.text)

lines = response.text.splitlines()
for line in lines:
  print(line)

for line in lines:
  if "花蓮" in line:
    # Split the line by commas and get the AQI value (index 2)
    aqi_value = line.split(',')[2]
    print(f"The AQI value for 花蓮 is: {aqi_value}")
    break # Assuming only one line contains "花蓮"